FROM node:20-alpine

WORKDIR /repo
RUN npm install -g pnpm

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml* ./
COPY backend/package.json ./backend/

RUN pnpm install --frozen-lockfile

WORKDIR /repo/backend

CMD ["sh", "-c", "npx prisma migrate dev --name init && npx ts-node -r tsconfig-paths/register src/main.ts"]
